apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-react
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - todo-react
      - key: env
        operator: In
        values:
          - staging
  template:
    metadata:
      labels:
        app: todo-react
        env: staging
    spec:
      containers:
      - name: todo-react
        image: gustysap/todo-react:latest
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: todo-react
spec:
  type: NodePort
  selector:
    app: todo-react
  ports:
  - port: 8010
    targetPort: 5000
    protocol: TCP