name: Build Push Deployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_push_docker:
    name: build and push docker todo react image
    runs-on: ubuntu-latest
    env: 
      APPLICATION_NAME: todo-react
    steps:
      - name: Cloning project
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: gustysap/${{ env.APPLICATION_NAME }}:${{ steps.vars.outputs.sha_short }}
  deployment_to_k8s:
    name: deployment to k8s
    needs: [build_and_push_docker]
    runs-on: ubuntu-latest
    env: 
      APPLICATION_NAME: todo-react
    steps:
      - name: Cloning project
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - name: change deployment.yaml image
        run: sed -i "s/todo-react:latest/todo-react:${{ steps.vars.outputs.sha_short }}/g" deployment.yaml
      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f deployment.yaml
